version: '3.7'
services:
  server:
    build: ./server
    command: yarn start
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
      - /app/node_modules
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
