version: "3.5"
services:
  data:
    build: ../data
    volumes:
      - ../data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/node_modules
    command: yarn start
    networks:
      - local_graphcool
    environment:
      GRAPHCOOL_HOST: localfaas

networks:
  local_graphcool:
    name: local_graphcool
    driver: bridge
