version: "3.5"
services:
  app:
    build: ../app
    ports:
      - "8444:8444"
    volumes:
      - ../app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - .graphcoolrc:/root/.graphcoolrc
    command: sleep 9999999999
    networks:
      - local_graphcool

networks:
  local_graphcool:
    name: local_graphcool
    driver: bridge
