version: '3.7'
services:
  file-server:
    image: tusd
    ports:
      - '1080:1080'
  # app:
  #   build: ./app
  #   command: yarn start
  #   depends_on:
  #     - file-server
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules
