version: "3.7"

services:
  db:
    image: postgres
  web:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
