version: "3.7"
services:
  server:
    container_name: "Server"
    build: ./server
    command: yarn start
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    entrypoint: ./entrypoint.sh
  db:
    container_name: "Postgres"
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/src:/var/lib/postgresql/src
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
